// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU3Xv3jNiwhK-rOlVa7ypT0y9Vv694BtM',
    appId: '1:220315283791:web:c428792215a208bf6dd53a',
    messagingSenderId: '220315283791',
    projectId: 'quiz-app-6055e',
    authDomain: 'quiz-app-6055e.firebaseapp.com',
    storageBucket: 'quiz-app-6055e.appspot.com',
    measurementId: 'G-NVJNT8C40W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAnq_Vj06O_5GTweSnRkv3ZMrgImamso',
    appId: '1:220315283791:android:008d0faeb95c9a6c6dd53a',
    messagingSenderId: '220315283791',
    projectId: 'quiz-app-6055e',
    storageBucket: 'quiz-app-6055e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1HY89tyGqf9wjYDNDoYc0BarS8LPg_48',
    appId: '1:220315283791:ios:8ebd5243d1ecb0c46dd53a',
    messagingSenderId: '220315283791',
    projectId: 'quiz-app-6055e',
    storageBucket: 'quiz-app-6055e.appspot.com',
    iosBundleId: 'com.tekzow.quizApp',
  );
}
